function simp = simpson3(f,a,b,n)

    h = (b-a)/n; % height of trapezoidal generated by numerical method
    simp = 0.0;

    for i = 1:n
        k1 = f(x(i));
        k2 = f(x(i+1));
        k3 = f(x(i+2));
        simp = simp + h/3*(k1+4*k2+k3);
    end

end